### ISSUE TITLE
user_email_list = [data[1].strip() for data in user_data_list[1:]] IndexError: list index out of range

### ISSUE THREAD

**Issue by gsiahaan** [elmoallistair/Google-IT-Automation-with-Python-Professional-Certificate#10]
https://github.com/elmoallistair/google-it-automation/blob/5306f55f15b2c2cfdb7ca19562f906f1f08da893/c2_python-operating-system/3_regular-expressions/graded-assessment/scripts/script.py#L31

**Comment by elmoallistair** [comment]
Seems either variable `data` or `user_data_list` are empty (or just contains 1 element)
Have you checked it?

**Comment by gsiahaan** [comment]
ohh I'm sorry...I just got this assignment, and I got the error.
Searching for alternative code still got error

I just realize, accidentally I add more empty row in the csv file.
Now it fixed.

**Comment by elmoallistair** [comment]
Alright, good luck on other assignments!
