### ISSUE TITLE
week 3 Assignment error for the capstone project

### ISSUE THREAD

**Issue by Debagnik** [elmoallistair/Google-IT-Automation-with-Python-Professional-Certificate#3]
locale.Error: unsupported locale setting

IDK why this is happening but please help

**Comment by elmoallistair** [comment]
Are you talking about this [assessment](https://github.com/elmoallistair/google-it-automation/tree/master/C6%20Automating%20Real-World%20Tasks%20with%20Python/M3%20Automatic%20Output%20Generation/Project) ?

**Comment by Debagnik** [comment]
Yes, To be specific the "cars.py" script is giving me headache

**Comment by elmoallistair** [comment]
*Discussion moved to Telegram chat*

**Comment by elmoallistair** [comment]
**Discussion moved to Telegram chat, seems we still not resolve this*

This is the problem
Line 31: `locale.setlocale(locale.LC_ALL, 'en_US.UTF8')`
Error msg: `locale.Error: unsupported locale setting`

Other references also have same setting

```
~$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by Debagnik** [comment]
I have contacted the qwiklabs support and they think that there are some issues with the version depreciation of python language on their servers and they seem to check let me know via my mail. I will keep you posted

**Comment by AJ-Walker** [comment]
I Have followed these step and it worked for me.
Can i share.

**Comment by elmoallistair** [comment]
Sure, let us know. 
Can you do pull request?

**Comment by AJ-Walker** [comment]
First i checked which locale was available using below command 
> locale -a
so, i got these output,
C
C.UTF-8
POSIX

I just replaced,
locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
with,
locale.setlocale(locale.LC_ALL, 'C.UTF-8')

**Comment by elmoallistair** [comment]
I have confirmed that this solution works and have updated the script  51611d6

![Screenshot_2020-11-29 Automatically Generate a PDF and send it by Email Qwiklabs](https://user-images.githubusercontent.com/55618192/100531172-6f783c80-322d-11eb-87d9-a82ce113f924.png)

Thanks~

**Comment by CanopusMicrosystems** [comment]
Run 
locale -a 
then use the output from that to replace en_US.UTF8

**Comment by aswathy-ma** [comment]
> First i checked which locale was available using below command
> 
> > locale -a
> > so, i got these output,
> > C
> > C.UTF-8
> > POSIX
> 
> I just replaced,
> locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
> with,
> locale.setlocale(locale.LC_ALL, 'C.UTF-8')

Thanks, It worked for me as well :)
