### ISSUE TITLE
Adding a .txt file

### ISSUE THREAD

**Issue by sean-flanagan** [elmoallistair/Google-IT-Automation-with-Python-Professional-Certificate#4]
Hey Elmo, wondering how you added the child of persia file to the notebook? Thanks!

**Comment by elmoallistair** [comment]
Hi,
You can go to dashboard by click on Jupyter logo 
![1](https://user-images.githubusercontent.com/55618192/102106199-da975500-3e62-11eb-836b-79fbc482ef96.png)
![2](https://user-images.githubusercontent.com/55618192/102106202-dbc88200-3e62-11eb-8d80-f49c0edd12f2.png)

or you can execute bash script directly on jupyter

```
!echo "some text" > some_file.txt
```

**Comment by sean-flanagan** [comment]
Great, thank you!

**Comment by sean-flanagan** [comment]
For some reason I'm still getting this error on the last cell, any ideas? 
![image](https://user-images.githubusercontent.com/36241594/102107503-ccfcb380-3dff-11eb-8199-bde7f74a8bcd.png)

**Comment by elmoallistair** [comment]
Have you run
```
!pip install wordcloud
````
and
```
import wordcloud
```
?

**Comment by sean-flanagan** [comment]
That helped! The last error I am getting is the following. Any last tips?
![image](https://user-images.githubusercontent.com/36241594/102113343-ed7c3c00-3e06-11eb-8535-9b8ddd412ca2.png)

**Comment by sean-flanagan** [comment]
Nevermind, I got it! Thanks Elmo!  😃

**Comment by Raagsi4u** [comment]
![image](https://user-images.githubusercontent.com/106095870/169847761-0bc6abd2-18c8-4609-8748-9a3525649aac.png)

can you help me out , how did you solved this...!?

**Comment by elmoallistair** [comment]
you haven't defined the `file_contents`  variable

check the second code cell:

```
file = open('path-to-your-file.txt','r')
file_contents = file.read()
```

**Comment by Raagsi4u** [comment]
![image](https://user-images.githubusercontent.com/106095870/169980525-fbf8bf0a-7811-4589-8de1-eab54b67d21e.png)

Yes i had tried your suggestion and got this..!

**Comment by elmoallistair** [comment]
Only use code from the last 2 lines 

Have a look at this snippet

![Screenshot_2022-05-24-15-22-01-934_com.github.android.jpg](https://user-images.githubusercontent.com/55618192/169984916-d9d3778c-20f1-4b02-8609-fdb08d9f5807.jpg)

**Comment by Raagsi4u** [comment]
ok But I'm getting this....!

![image](https://user-images.githubusercontent.com/106095870/169988310-4e848d76-9926-4f00-b5c2-9b71fe3884a6.png)

**Comment by Raagsi4u** [comment]
Hello can any one help me out please....!

**Comment by Raagsi4u** [comment]
> ok But I'm getting this....!
> 
> ![image](https://user-images.githubusercontent.com/106095870/169988310-4e848d76-9926-4f00-b5c2-9b71fe3884a6.png)

Hello can any one help me out please....!

**Comment by Adityasharma3010** [comment]
> > ok But I'm getting this....!
> > ![image](https://user-images.githubusercontent.com/106095870/169988310-4e848d76-9926-4f00-b5c2-9b71fe3884a6.png)
> 
> Hello can any one help me out please....!

u need to add a text file in jupiter then run the code
