### ISSUE TITLE
Getting Error while Adding a .txt

### ISSUE THREAD

**Issue by Raagsi4u** [elmoallistair/Google-IT-Automation-with-Python-Professional-Certificate#8]
![image](https://user-images.githubusercontent.com/106095870/170229012-57404fd4-3bae-468a-9884-5b6f3995767a.png)

waiting for your Help...!

**Comment by elmoallistair** [comment]
The file `children-of-persia.txt` doesnt exist yet

Check how to create the file here: https://github.com/elmoallistair/google-it-automation/issues/4#issuecomment-744550263

**Comment by Shibli2316** [comment]
I guess you haven't made the file yet and using read mode to access it and that is causing the trouble

**Comment by saiavinash77** [comment]
the file is not occur in your directory ,so thats why its showing like that
